name:                text-chat-bot
version:             0.1.0.0
github:              "githubuser/text-chat-bot"
license:             BSD3
author:              "Yan Shkurinsky"
maintainer:          "yan.shkurinsky@gmail.com"
copyright:           "2019 Yan Shkurinsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/text-chat-bot#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- aeson
- async
- bytestring

library:
  source-dirs: src

executables:
  text-chat-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-chat-bot

tests:
  text-chat-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-chat-bot
